# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    view:
        formats:
            json: true
        failed_validation: HTTP_BAD_REQUEST
        mime_types:
            json: ['application/json; charset=utf-8', 'application/json']
        view_response_listener:  force

