security:

    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12

    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        token_user_provider:
            id: App\Security\TokenUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            stateless: true
            methods: [POST]
            anonymous: ~
            logout: ~
            simple_preauth:
                authenticator: App\Security\TokenAuthenticator
            provider: token_user_provider
        main:
            anonymous: ~

            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/cookbook/security/form_login_setup.html
