language: php

sudo: false

notifications:
  email:
    on_success: never
    on_failure: change

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0

before-install:
  - composer self-update

install:
  - composer install
  - cp app/config/parameters.yml.dist app/config/parameters.yml
#  - php bin/console doctrine:database:create --env=test
#  - php bin/console doctrine:migrations:migrate --no-interaction --env=test
#  - php bin/console doctrine:fixtures:load -n --env=test

script:
  - phpunit --coverage-clover=coverage.xml

after_success:
- bash <(curl -s https://codecov.io/bash)