language: php
php:
  - 7.1.11

sudo: required

env:
  global:
    - APP_ENV=test
    - DOCKER_USER=monsieurbon
    - secure: "tsv/b0obUP09DC3NH+W/0SNmSih2HNSttcuPoTCBrMIe4AppJWDs5lbUBrO3uOqj6Utcak/2yIZQcbIvIFogI+lk9jUAuiefkJpHvVubpNOt1iE2alc1og+Z+IBs9/IiVC9qm9D50+GEiyTfnuPCJW8oGlHROvNOV67FQC4KrgzUI0QH+DHh5bFZvyxXAbeWosurIrF6Rh1bw2wzYryTdEyBb7FXuq9+qNILUXiDjhzmH04Y47gJ/TtwIe0X1mWjLid0RHq/hQGdFsov60GLwGqiR606W0tCAYGs6B2ZHKHPPscq/WgCVtduD5BxKWRgwGNBSeoqiLW+RRANTSUNStwbLEJXwiKgyQ1KceEbGv+Y0QnOFMmB7dkFcGcd+dhtgQ9DM4jWNkcXupx5I6Vvo8lMjDNm8hXXjFIUumB6mwxlWsPNGYyaND2XSAxaxLhUVW692Pi4KWowbrxwzRAyPqLHW2xT6JAmUecNYpo4S0FDyiW858X4U0mRMWHHOH3rPblXj8EWLVDKG0e6HWcK15FXKUjIuq3B9+eh2M5tjv39Pn2zBIQ9tF25fzwCiPpX+rO3t6wdPbWJ1JC7LZGotg9qhNdog00o285yq5+/pRfjVXUv/rvw6y9b+++OedG1Yq5czO7QSlv8ois9iuYjCom/BaDWGQkxWt3jQUVEBDE="

addons:
  chrome: stable
  sonarcloud:
    organization: "monsieurbon-github"
    token:
      secure: "NRjfN+CpgyylNyPihQ6RUK4lEkI9BtR9aLbOd2GKgDWVTdX1MMv6P2kaTmeE085oRw/XM1iXqZSikt7EHbyIH771LkIcYTpIfSW5392gGDsgvqxvNQlywybM9q5lbBFA+ho543xs/KxOfqHAZxeLT0xkv7zD/BBJnidRLFpN7ANC6CxOKpWol6DiSdth7QX6RbXr+nImQOHUn79y6EAUjHF7qPfqfSnd39WB2EeHCcbKnmTWOswNlh6xxB9lWT19G3CBzR12GZRUGYlq0HQ4FNqZ7hHHyvRtSYNkOjBPGBgbRy8wVksn5TCnaQli8qZHmqOwrPmWtIb3Zsu1I4OUVu+hbaIoKWWg5qon9n6V9yVxm0yducasXGdMvCcfPRRGd0t7gDss31yloXYv7myVl1oC4AKyjcKXO+3RFcqlxSIbFjAdJH+68/u8zMS5XU5NDIc/1ZgCMQnmtc3Gb3xZKNFfOJY9wPRUaJstYPD6xMocg2eYtXKWM2DKH+mXctwKSi977iGi7NBaaTqmE8Qg+eCtV+RW9VLZDbiXRruZY/ytU03ZMfr5mzwipbavJDGWMsWh2PVsvfWpIXNVcGCQZgrn9o4lNN9BHTVDJZtYnAELYGSAcLN157Si7kHSs+8Uyab3cou+ruJG1jMYa6pfJ39rHJQAhcu2PELIzqd2gI4="

jdk:
  - oraclejdk8

notifications:
  email:
    on_success: never
    on_failure: change

services:
  - mysql

cache:
  yarn: true
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.sonar/cache

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
  - composer self-update
  - nvm install 10.3.0

install:
  - composer install
  - yarn install

before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('symfony') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - bin/console doctrine:database:create --if-not-exists
  - bin/console doctrine:migrations:migrate -n
  - bin/console doctrine:fixtures:load -n
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - phpunit --coverage-clover=coverage.xml
  - yarn test:coverage
  - yarn e2e
  - yarn build:prod

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - sonar-scanner

deploy:
  skip_cleanup: true
  provider: script
  script: scripts/build_docker.sh $DOCKER_USER $DOCKER_PASS $TRAVIS_TAG
  on:
    tags: true
