language: php
php:
  - 7.1.11

sudo: false

addons:
  chrome: stable
  sonarcloud:
    organization: "monsieurbon-github"
    token:
      secure: "NRjfN+CpgyylNyPihQ6RUK4lEkI9BtR9aLbOd2GKgDWVTdX1MMv6P2kaTmeE085oRw/XM1iXqZSikt7EHbyIH771LkIcYTpIfSW5392gGDsgvqxvNQlywybM9q5lbBFA+ho543xs/KxOfqHAZxeLT0xkv7zD/BBJnidRLFpN7ANC6CxOKpWol6DiSdth7QX6RbXr+nImQOHUn79y6EAUjHF7qPfqfSnd39WB2EeHCcbKnmTWOswNlh6xxB9lWT19G3CBzR12GZRUGYlq0HQ4FNqZ7hHHyvRtSYNkOjBPGBgbRy8wVksn5TCnaQli8qZHmqOwrPmWtIb3Zsu1I4OUVu+hbaIoKWWg5qon9n6V9yVxm0yducasXGdMvCcfPRRGd0t7gDss31yloXYv7myVl1oC4AKyjcKXO+3RFcqlxSIbFjAdJH+68/u8zMS5XU5NDIc/1ZgCMQnmtc3Gb3xZKNFfOJY9wPRUaJstYPD6xMocg2eYtXKWM2DKH+mXctwKSi977iGi7NBaaTqmE8Qg+eCtV+RW9VLZDbiXRruZY/ytU03ZMfr5mzwipbavJDGWMsWh2PVsvfWpIXNVcGCQZgrn9o4lNN9BHTVDJZtYnAELYGSAcLN157Si7kHSs+8Uyab3cou+ruJG1jMYa6pfJ39rHJQAhcu2PELIzqd2gI4="

jdk:
  - oraclejdk8

notifications:
  email:
    on_success: never
    on_failure: change

services:
  - mysql

cache:
  yarn: true
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.sonar/cache

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
  - composer self-update
  - nvm install 8.5.0

install:
  - composer install
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - yarn install

before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('symfony') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - bin/console doctrine:database:drop --if-exists --force --env=test
  - bin/console doctrine:database:create --if-not-exists --env=test
  - bin/console doctrine:migrations:migrate -n --env=test
  - bin/console doctrine:fixtures:load -n --env=test
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - phpunit --coverage-clover=coverage.xml
  - yarn test:coverage
  - yarn e2e

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - sonar-scanner
