<?php

namespace App\Repository;

use App\Entity\ApiToken;
use Doctrine\ORM\EntityRepository;

/**
 * ApiTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiTokenRepository extends EntityRepository
{
    /**
     * @param $token
     *
     * @return ApiToken
     */
    public function findValidToken($token)
    {
        $query = $this->getEntityManager()->createQuery(
            'SELECT t
            FROM App\Entity\ApiToken t
            WHERE t.token = SHA2(CONCAT_WS(\'\', t.salt, :token), 512)
            AND t.validUntil > :validUntil'
        )->setParameter('token', $token)
         ->setParameter('validUntil', new \DateTime('now'));

        return $query->getOneOrNullResult();
    }
}
