<?php

namespace App\Repository;

use App\Entity\User;

/**
 * TasklistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TasklistRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param User $user
     * @return array
     */
    public function findAllWithAccess(User $user)
    {
        $query = $this->createQueryBuilder('t')
            ->innerJoin('t.owner', 'o')
            ->leftJoin('t.users', 'u')
            ->where('o.id = :user_id')
            ->orWhere('u.id = :user_id')
            ->setParameter('user_id', $user->getId())
            ->getQuery();

        return $query->getResult();
    }
}
