#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

fallback:
    path: /{req}
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /
        permanent: true
    requirements:
        req: ".+"